<section id="boas-vindas" class="content">
	<div id="animated-unicamp-svg"></div>

	<h1>
		Seja bem-vindo(a) ao melhor curso de Engenharia Elétrica da América Latina!
	</h1>
	<h4>
		Parabéns Bixo / Bixete! Agora você faz parte do seleto grupo de pessoas que podem desfrutar da incrível infra-estrutura de nossa universidade e ainda conviver com futuros grandes nomes da engenharia.
	</h4>
</section>
